### PR TITLE
Fix compatibility with D 2.099

### LINKED ISSUE #144: Bump from d789306 to 2454a72 broke the build
Compilation flags used `--mtriple=x86_64-linux-gnu -w --preview=dip1000 --preview=dtorfields --preview=fieldwise -O --release --boundscheck=off` (this is a precheck compilation phase).

Example code for argparse options (the code that produces the error):
```d
struct ViewerOptions
{
    @(MutuallyExclusive())
    {
        @(NamedArgument("local").Description("Choose a local connection").Optional())
        bool local = true;

        @(NamedArgument("remote").Description("Choose a remote connection").Optional())
        string remoteAddress = null;
    }

    @(NamedArgument("serverPath").Description("Path the server binary").Optional())
    string serverPath = null;

    @(NamedArgument("p", "path").Description("Path of the dumping blobs").Optional())
    string localPath = defaultPath;

    @(NamedArgument("namespace").Description("Namespace to interleave").Optional())
    string namespace = null;

    @(NamedArgument("d", "debug").Description("Enable debugging").Optional())
    bool debugging = false;
}
```

```
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/command.d(278): Error: CTFE failed because of previous errors in `getMemberArgumentUDA`
/opt/hostedtoolcache/dc/ldc2-1.30.0/x64/ldc2-1.30.0-linux-x86_64/bin/../import/std/meta.d(652): Error: template instance `argparse.internal.command.TypeTraits!(Config('=', '\xff', '-', "--", true, false, true, Style(TextStyle("\x1b[1"), TextStyle("\x1b[1"), TextStyle("\x1b[1;4"), TextStyle("\x1b[93"), TextStyle("\x1b[3"), TextStyle("\x1b[93"), TextStyle("\x1b[31")), StylingMode.off, null), ViewerOptions).fun!"serverPath"` error instantiating
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/command.d(286):        instantiated from here: `staticMap!(getArgumentUDA, "local", "remoteAddress", "serverPath", "localPath", "namespace", "debugging")`
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/command.d(358):        instantiated from here: `TypeTraits!(Config('=', '\xff', '-', "--", true, false, true, Style(TextStyle("\x1b[1"), TextStyle("\x1b[1"), TextStyle("\x1b[1;4"), TextStyle("\x1b[93"), TextStyle("\x1b[3"), TextStyle("\x1b[93"), TextStyle("\x1b[31")), StylingMode.off, null), ViewerOptions)`
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/parser.d(603):        instantiated from here: `createCommand!(Config('=', '\xff', '-', "--", true, false, true, Style(TextStyle("\x1b[1"), TextStyle("\x1b[1"), TextStyle("\x1b[1;4"), TextStyle("\x1b[93"), TextStyle("\x1b[3"), TextStyle("\x1b[93"), TextStyle("\x1b[31")), StylingMode.off, null), ViewerOptions)`
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/parser.d(628):        ... (2 instantiations, -v to show) ...
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/api/cli.d(192):        instantiated from here: `CLI!(Config('=', '\xff', '-', "--", true, false, true, Style(TextStyle("\x1b[1"), TextStyle("\x1b[1"), TextStyle("\x1b[1;4"), TextStyle("\x1b[93"), TextStyle("\x1b[3"), TextStyle("\x1b[93"), TextStyle("\x1b[31")), StylingMode.autodetect, null), ViewerOptions)`
source/wtracer/viewer/main.d(273):        instantiated from here: `CLI!(ViewerOptions)`
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/command.d(278): Error: CTFE failed because of previous errors in `getMemberArgumentUDA`
/opt/hostedtoolcache/dc/ldc2-1.30.0/x64/ldc2-1.30.0-linux-x86_64/bin/../import/std/meta.d(652): Error: template instance `argparse.internal.command.TypeTraits!(Config('=', '\xff', '-', "--", true, false, true, Style(TextStyle("\x1b[1"), TextStyle("\x1b[1"), TextStyle("\x1b[1;4"), TextStyle("\x1b[93"), TextStyle("\x1b[3"), TextStyle("\x1b[93"), TextStyle("\x1b[31")), StylingMode.off, null), ViewerOptions).fun!"localPath"` error instantiating
```

<details>
<summary>More complete log:</summary>

```
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/argumentudahelpers.d(77): Error: first argument is not a symbol
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/argumentudahelpers.d(80):        while evaluating: `static assert(typeUDAs.length <= 1)`
/opt/hostedtoolcache/dc/ldc2-1.30.0/x64/ldc2-1.30.0-linux-x86_64/bin/../import/std/meta.d(652): Error: template instance `argparse.internal.command.TypeTraits!(Config('=', '\xff', '-', "--", true, false, true, Style(TextStyle("\x1b[1"), TextStyle("\x1b[1"), TextStyle("\x1b[1;4"), TextStyle("\x1b[93"), TextStyle("\x1b[3"), TextStyle("\x1b[93"), TextStyle("\x1b[31")), StylingMode.on, null), ViewerOptions).fun!"local"` error instantiating
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/command.d(286):        instantiated from here: `staticMap!(getArgumentUDA, "local", "remoteAddress", "serverPath", "localPath", "namespace", "debugging")`
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/command.d(358):        instantiated from here: `TypeTraits!(Config('=', '\xff', '-', "--", true, false, true, Style(TextStyle("\x1b[1"), TextStyle("\x1b[1"), TextStyle("\x1b[1;4"), TextStyle("\x1b[93"), TextStyle("\x1b[3"), TextStyle("\x1b[93"), TextStyle("\x1b[31")), StylingMode.on, null), ViewerOptions)`
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/parser.d(603):        instantiated from here: `createCommand!(Config('=', '\xff', '-', "--", true, false, true, Style(TextStyle("\x1b[1"), TextStyle("\x1b[1"), TextStyle("\x1b[1;4"), TextStyle("\x1b[93"), TextStyle("\x1b[3"), TextStyle("\x1b[93"), TextStyle("\x1b[31")), StylingMode.on, null), ViewerOptions)`
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/parser.d(626):        ... (2 instantiations, -v to show) ...
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/api/cli.d(192):        instantiated from here: `CLI!(Config('=', '\xff', '-', "--", true, false, true, Style(TextStyle("\x1b[1"), TextStyle("\x1b[1"), TextStyle("\x1b[1;4"), TextStyle("\x1b[93"), TextStyle("\x1b[3"), TextStyle("\x1b[93"), TextStyle("\x1b[31")), StylingMode.autodetect, null), ViewerOptions)`
source/wtracer/viewer/main.d(273):        instantiated from here: `CLI!(ViewerOptions)`
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/argumentudahelpers.d(77): Error: first argument is not a symbol
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/argumentudahelpers.d(80):        while evaluating: `static assert(typeUDAs.length <= 1)`
/opt/hostedtoolcache/dc/ldc2-1.30.0/x64/ldc2-1.30.0-linux-x86_64/bin/../import/std/meta.d(652): Error: template instance `argparse.internal.command.TypeTraits!(Config('=', '\xff', '-', "--", true, false, true, Style(TextStyle("\x1b[1"), TextStyle("\x1b[1"), TextStyle("\x1b[1;4"), TextStyle("\x1b[93"), TextStyle("\x1b[3"), TextStyle("\x1b[93"), TextStyle("\x1b[31")), StylingMode.on, null), ViewerOptions).fun!"remoteAddress"` error instantiating
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/command.d(286):        instantiated from here: `staticMap!(getArgumentUDA, "local", "remoteAddress", "serverPath", "localPath", "namespace", "debugging")`
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/command.d(358):        instantiated from here: `TypeTraits!(Config('=', '\xff', '-', "--", true, false, true, Style(TextStyle("\x1b[1"), TextStyle("\x1b[1"), TextStyle("\x1b[1;4"), TextStyle("\x1b[93"), TextStyle("\x1b[3"), TextStyle("\x1b[93"), TextStyle("\x1b[31")), StylingMode.on, null), ViewerOptions)`
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/parser.d(603):        instantiated from here: `createCommand!(Config('=', '\xff', '-', "--", true, false, true, Style(TextStyle("\x1b[1"), TextStyle("\x1b[1"), TextStyle("\x1b[1;4"), TextStyle("\x1b[93"), TextStyle("\x1b[3"), TextStyle("\x1b[93"), TextStyle("\x1b[31")), StylingMode.on, null), ViewerOptions)`
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/parser.d(626):        ... (2 instantiations, -v to show) ...
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/api/cli.d(192):        instantiated from here: `CLI!(Config('=', '\xff', '-', "--", true, false, true, Style(TextStyle("\x1b[1"), TextStyle("\x1b[1"), TextStyle("\x1b[1;4"), TextStyle("\x1b[93"), TextStyle("\x1b[3"), TextStyle("\x1b[93"), TextStyle("\x1b[31")), StylingMode.autodetect, null), ViewerOptions)`
source/wtracer/viewer/main.d(273):        instantiated from here: `CLI!(ViewerOptions)`
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/argumentudahelpers.d(77): Error: first argument is not a symbol
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/argumentudahelpers.d(80):        while evaluating: `static assert(typeUDAs.length <= 1)`
/opt/hostedtoolcache/dc/ldc2-1.30.0/x64/ldc2-1.30.0-linux-x86_64/bin/../import/std/meta.d(652): Error: template instance `argparse.internal.command.TypeTraits!(Config('=', '\xff', '-', "--", true, false, true, Style(TextStyle("\x1b[1"), TextStyle("\x1b[1"), TextStyle("\x1b[1;4"), TextStyle("\x1b[93"), TextStyle("\x1b[3"), TextStyle("\x1b[93"), TextStyle("\x1b[31")), StylingMode.on, null), ViewerOptions).fun!"serverPath"` error instantiating
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/command.d(286):        instantiated from here: `staticMap!(getArgumentUDA, "local", "remoteAddress", "serverPath", "localPath", "namespace", "debugging")`
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/command.d(358):        instantiated from here: `TypeTraits!(Config('=', '\xff', '-', "--", true, false, true, Style(TextStyle("\x1b[1"), TextStyle("\x1b[1"), TextStyle("\x1b[1;4"), TextStyle("\x1b[93"), TextStyle("\x1b[3"), TextStyle("\x1b[93"), TextStyle("\x1b[31")), StylingMode.on, null), ViewerOptions)`
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/parser.d(603):        instantiated from here: `createCommand!(Config('=', '\xff', '-', "--", true, false, true, Style(TextStyle("\x1b[1"), TextStyle("\x1b[1"), TextStyle("\x1b[1;4"), TextStyle("\x1b[93"), TextStyle("\x1b[3"), TextStyle("\x1b[93"), TextStyle("\x1b[31")), StylingMode.on, null), ViewerOptions)`
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/parser.d(626):        ... (2 instantiations, -v to show) ...
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/api/cli.d(192):        instantiated from here: `CLI!(Config('=', '\xff', '-', "--", true, false, true, Style(TextStyle("\x1b[1"), TextStyle("\x1b[1"), TextStyle("\x1b[1;4"), TextStyle("\x1b[93"), TextStyle("\x1b[3"), TextStyle("\x1b[93"), TextStyle("\x1b[31")), StylingMode.autodetect, null), ViewerOptions)`
source/wtracer/viewer/main.d(273):        instantiated from here: `CLI!(ViewerOptions)`
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/argumentudahelpers.d(77): Error: first argument is not a symbol
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/argumentudahelpers.d(80):        while evaluating: `static assert(typeUDAs.length <= 1)`
/opt/hostedtoolcache/dc/ldc2-1.30.0/x64/ldc2-1.30.0-linux-x86_64/bin/../import/std/meta.d(652): Error: template instance `argparse.internal.command.TypeTraits!(Config('=', '\xff', '-', "--", true, false, true, Style(TextStyle("\x1b[1"), TextStyle("\x1b[1"), TextStyle("\x1b[1;4"), TextStyle("\x1b[93"), TextStyle("\x1b[3"), TextStyle("\x1b[93"), TextStyle("\x1b[31")), StylingMode.on, null), ViewerOptions).fun!"localPath"` error instantiating
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/command.d(286):        instantiated from here: `staticMap!(getArgumentUDA, "local", "remoteAddress", "serverPath", "localPath", "namespace", "debugging")`
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/command.d(358):        instantiated from here: `TypeTraits!(Config('=', '\xff', '-', "--", true, false, true, Style(TextStyle("\x1b[1"), TextStyle("\x1b[1"), TextStyle("\x1b[1;4"), TextStyle("\x1b[93"), TextStyle("\x1b[3"), TextStyle("\x1b[93"), TextStyle("\x1b[31")), StylingMode.on, null), ViewerOptions)`
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/parser.d(603):        instantiated from here: `createCommand!(Config('=', '\xff', '-', "--", true, false, true, Style(TextStyle("\x1b[1"), TextStyle("\x1b[1"), TextStyle("\x1b[1;4"), TextStyle("\x1b[93"), TextStyle("\x1b[3"), TextStyle("\x1b[93"), TextStyle("\x1b[31")), StylingMode.on, null), ViewerOptions)`
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/parser.d(626):        ... (2 instantiations, -v to show) ...
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/api/cli.d(192):        instantiated from here: `CLI!(Config('=', '\xff', '-', "--", true, false, true, Style(TextStyle("\x1b[1"), TextStyle("\x1b[1"), TextStyle("\x1b[1;4"), TextStyle("\x1b[93"), TextStyle("\x1b[3"), TextStyle("\x1b[93"), TextStyle("\x1b[31")), StylingMode.autodetect, null), ViewerOptions)`
source/wtracer/viewer/main.d(273):        instantiated from here: `CLI!(ViewerOptions)`
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/argumentudahelpers.d(77): Error: first argument is not a symbol
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/argumentudahelpers.d(80):        while evaluating: `static assert(typeUDAs.length <= 1)`
/opt/hostedtoolcache/dc/ldc2-1.30.0/x64/ldc2-1.30.0-linux-x86_64/bin/../import/std/meta.d(652): Error: template instance `argparse.internal.command.TypeTraits!(Config('=', '\xff', '-', "--", true, false, true, Style(TextStyle("\x1b[1"), TextStyle("\x1b[1"), TextStyle("\x1b[1;4"), TextStyle("\x1b[93"), TextStyle("\x1b[3"), TextStyle("\x1b[93"), TextStyle("\x1b[31")), StylingMode.on, null), ViewerOptions).fun!"namespace"` error instantiating
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/command.d(286):        instantiated from here: `staticMap!(getArgumentUDA, "local", "remoteAddress", "serverPath", "localPath", "namespace", "debugging")`
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/command.d(358):        instantiated from here: `TypeTraits!(Config('=', '\xff', '-', "--", true, false, true, Style(TextStyle("\x1b[1"), TextStyle("\x1b[1"), TextStyle("\x1b[1;4"), TextStyle("\x1b[93"), TextStyle("\x1b[3"), TextStyle("\x1b[93"), TextStyle("\x1b[31")), StylingMode.on, null), ViewerOptions)`
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/parser.d(603):        instantiated from here: `createCommand!(Config('=', '\xff', '-', "--", true, false, true, Style(TextStyle("\x1b[1"), TextStyle("\x1b[1"), TextStyle("\x1b[1;4"), TextStyle("\x1b[93"), TextStyle("\x1b[3"), TextStyle("\x1b[93"), TextStyle("\x1b[31")), StylingMode.on, null), ViewerOptions)`
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/parser.d(626):        ... (2 instantiations, -v to show) ...
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/api/cli.d(192):        instantiated from here: `CLI!(Config('=', '\xff', '-', "--", true, false, true, Style(TextStyle("\x1b[1"), TextStyle("\x1b[1"), TextStyle("\x1b[1;4"), TextStyle("\x1b[93"), TextStyle("\x1b[3"), TextStyle("\x1b[93"), TextStyle("\x1b[31")), StylingMode.autodetect, null), ViewerOptions)`
source/wtracer/viewer/main.d(273):        instantiated from here: `CLI!(ViewerOptions)`
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/argumentudahelpers.d(77): Error: first argument is not a symbol
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/argumentudahelpers.d(80):        while evaluating: `static assert(typeUDAs.length <= 1)`
/opt/hostedtoolcache/dc/ldc2-1.30.0/x64/ldc2-1.30.0-linux-x86_64/bin/../import/std/meta.d(652): Error: template instance `argparse.internal.command.TypeTraits!(Config('=', '\xff', '-', "--", true, false, true, Style(TextStyle("\x1b[1"), TextStyle("\x1b[1"), TextStyle("\x1b[1;4"), TextStyle("\x1b[93"), TextStyle("\x1b[3"), TextStyle("\x1b[93"), TextStyle("\x1b[31")), StylingMode.on, null), ViewerOptions).fun!"debugging"` error instantiating
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/command.d(286):        instantiated from here: `staticMap!(getArgumentUDA, "local", "remoteAddress", "serverPath", "localPath", "namespace", "debugging")`
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/command.d(358):        instantiated from here: `TypeTraits!(Config('=', '\xff', '-', "--", true, false, true, Style(TextStyle("\x1b[1"), TextStyle("\x1b[1"), TextStyle("\x1b[1;4"), TextStyle("\x1b[93"), TextStyle("\x1b[3"), TextStyle("\x1b[93"), TextStyle("\x1b[31")), StylingMode.on, null), ViewerOptions)`
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/parser.d(603):        instantiated from here: `createCommand!(Config('=', '\xff', '-', "--", true, false, true, Style(TextStyle("\x1b[1"), TextStyle("\x1b[1"), TextStyle("\x1b[1;4"), TextStyle("\x1b[93"), TextStyle("\x1b[3"), TextStyle("\x1b[93"), TextStyle("\x1b[31")), StylingMode.on, null), ViewerOptions)`
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/parser.d(626):        ... (2 instantiations, -v to show) ...
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/api/cli.d(192):        instantiated from here: `CLI!(Config('=', '\xff', '-', "--", true, false, true, Style(TextStyle("\x1b[1"), TextStyle("\x1b[1"), TextStyle("\x1b[1;4"), TextStyle("\x1b[93"), TextStyle("\x1b[3"), TextStyle("\x1b[93"), TextStyle("\x1b[31")), StylingMode.autodetect, null), ViewerOptions)`
source/wtracer/viewer/main.d(273):        instantiated from here: `CLI!(ViewerOptions)`
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/command.d(278): Error: CTFE failed because of previous errors in `getMemberArgumentUDA`
/opt/hostedtoolcache/dc/ldc2-1.30.0/x64/ldc2-1.30.0-linux-x86_64/bin/../import/std/meta.d(652): Error: template instance `argparse.internal.command.TypeTraits!(Config('=', '\xff', '-', "--", true, false, true, Style(TextStyle("\x1b[1"), TextStyle("\x1b[1"), TextStyle("\x1b[1;4"), TextStyle("\x1b[93"), TextStyle("\x1b[3"), TextStyle("\x1b[93"), TextStyle("\x1b[31")), StylingMode.off, null), ViewerOptions).fun!"local"` error instantiating
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/command.d(286):        instantiated from here: `staticMap!(getArgumentUDA, "local", "remoteAddress", "serverPath", "localPath", "namespace", "debugging")`
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/command.d(358):        instantiated from here: `TypeTraits!(Config('=', '\xff', '-', "--", true, false, true, Style(TextStyle("\x1b[1"), TextStyle("\x1b[1"), TextStyle("\x1b[1;4"), TextStyle("\x1b[93"), TextStyle("\x1b[3"), TextStyle("\x1b[93"), TextStyle("\x1b[31")), StylingMode.off, null), ViewerOptions)`
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/parser.d(603):        instantiated from here: `createCommand!(Config('=', '\xff', '-', "--", true, false, true, Style(TextStyle("\x1b[1"), TextStyle("\x1b[1"), TextStyle("\x1b[1;4"), TextStyle("\x1b[93"), TextStyle("\x1b[3"), TextStyle("\x1b[93"), TextStyle("\x1b[31")), StylingMode.off, null), ViewerOptions)`
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/parser.d(628):        ... (2 instantiations, -v to show) ...
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/api/cli.d(192):        instantiated from here: `CLI!(Config('=', '\xff', '-', "--", true, false, true, Style(TextStyle("\x1b[1"), TextStyle("\x1b[1"), TextStyle("\x1b[1;4"), TextStyle("\x1b[93"), TextStyle("\x1b[3"), TextStyle("\x1b[93"), TextStyle("\x1b[31")), StylingMode.autodetect, null), ViewerOptions)`
source/wtracer/viewer/main.d(273):        instantiated from here: `CLI!(ViewerOptions)`
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/command.d(278): Error: CTFE failed because of previous errors in `getMemberArgumentUDA`
/opt/hostedtoolcache/dc/ldc2-1.30.0/x64/ldc2-1.30.0-linux-x86_64/bin/../import/std/meta.d(652): Error: template instance `argparse.internal.command.TypeTraits!(Config('=', '\xff', '-', "--", true, false, true, Style(TextStyle("\x1b[1"), TextStyle("\x1b[1"), TextStyle("\x1b[1;4"), TextStyle("\x1b[93"), TextStyle("\x1b[3"), TextStyle("\x1b[93"), TextStyle("\x1b[31")), StylingMode.off, null), ViewerOptions).fun!"remoteAddress"` error instantiating
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/command.d(286):        instantiated from here: `staticMap!(getArgumentUDA, "local", "remoteAddress", "serverPath", "localPath", "namespace", "debugging")`
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/command.d(358):        instantiated from here: `TypeTraits!(Config('=', '\xff', '-', "--", true, false, true, Style(TextStyle("\x1b[1"), TextStyle("\x1b[1"), TextStyle("\x1b[1;4"), TextStyle("\x1b[93"), TextStyle("\x1b[3"), TextStyle("\x1b[93"), TextStyle("\x1b[31")), StylingMode.off, null), ViewerOptions)`
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/parser.d(603):        instantiated from here: `createCommand!(Config('=', '\xff', '-', "--", true, false, true, Style(TextStyle("\x1b[1"), TextStyle("\x1b[1"), TextStyle("\x1b[1;4"), TextStyle("\x1b[93"), TextStyle("\x1b[3"), TextStyle("\x1b[93"), TextStyle("\x1b[31")), StylingMode.off, null), ViewerOptions)`
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/parser.d(628):        ... (2 instantiations, -v to show) ...
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/api/cli.d(192):        instantiated from here: `CLI!(Config('=', '\xff', '-', "--", true, false, true, Style(TextStyle("\x1b[1"), TextStyle("\x1b[1"), TextStyle("\x1b[1;4"), TextStyle("\x1b[93"), TextStyle("\x1b[3"), TextStyle("\x1b[93"), TextStyle("\x1b[31")), StylingMode.autodetect, null), ViewerOptions)`
source/wtracer/viewer/main.d(273):        instantiated from here: `CLI!(ViewerOptions)`
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/command.d(278): Error: CTFE failed because of previous errors in `getMemberArgumentUDA`
/opt/hostedtoolcache/dc/ldc2-1.30.0/x64/ldc2-1.30.0-linux-x86_64/bin/../import/std/meta.d(652): Error: template instance `argparse.internal.command.TypeTraits!(Config('=', '\xff', '-', "--", true, false, true, Style(TextStyle("\x1b[1"), TextStyle("\x1b[1"), TextStyle("\x1b[1;4"), TextStyle("\x1b[93"), TextStyle("\x1b[3"), TextStyle("\x1b[93"), TextStyle("\x1b[31")), StylingMode.off, null), ViewerOptions).fun!"serverPath"` error instantiating
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/command.d(286):        instantiated from here: `staticMap!(getArgumentUDA, "local", "remoteAddress", "serverPath", "localPath", "namespace", "debugging")`
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/command.d(358):        instantiated from here: `TypeTraits!(Config('=', '\xff', '-', "--", true, false, true, Style(TextStyle("\x1b[1"), TextStyle("\x1b[1"), TextStyle("\x1b[1;4"), TextStyle("\x1b[93"), TextStyle("\x1b[3"), TextStyle("\x1b[93"), TextStyle("\x1b[31")), StylingMode.off, null), ViewerOptions)`
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/parser.d(603):        instantiated from here: `createCommand!(Config('=', '\xff', '-', "--", true, false, true, Style(TextStyle("\x1b[1"), TextStyle("\x1b[1"), TextStyle("\x1b[1;4"), TextStyle("\x1b[93"), TextStyle("\x1b[3"), TextStyle("\x1b[93"), TextStyle("\x1b[31")), StylingMode.off, null), ViewerOptions)`
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/parser.d(628):        ... (2 instantiations, -v to show) ...
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/api/cli.d(192):        instantiated from here: `CLI!(Config('=', '\xff', '-', "--", true, false, true, Style(TextStyle("\x1b[1"), TextStyle("\x1b[1"), TextStyle("\x1b[1;4"), TextStyle("\x1b[93"), TextStyle("\x1b[3"), TextStyle("\x1b[93"), TextStyle("\x1b[31")), StylingMode.autodetect, null), ViewerOptions)`
source/wtracer/viewer/main.d(273):        instantiated from here: `CLI!(ViewerOptions)`
/home/runner/work/wtracer/wtracer/3rdparty/argparse/source/argparse/internal/command.d(278): Error: CTFE failed because of previous errors in `getMemberArgumentUDA`
/opt/hostedtoolcache/dc/ldc2-1.30.0/x64/ldc2-1.30.0-linux-x86_64/bin/../import/std/meta.d(652): Error: template instance `argparse.internal.command.TypeTraits!(Config('=', '\xff', '-', "--", true, false, true, Style(TextStyle("\x1b[1"), TextStyle("\x1b[1"), TextStyle("\x1b[1;4"), TextStyle("\x1b[93"), TextStyle("\x1b[3"), TextStyle("\x1b[93"), TextStyle("\x1b[31")), StylingMode.off, null), ViewerOptions).fun!"localPath"` error instantiating
```
</details>

### PR DESCRIPTION
**Pull request by SirNickolas**
Closes #144.

I’m planning to reduce the minimal required version of the D frontend down to 2.095. Why this version? Because I tried 2.094, and the compiler failed to infer that (generated) `opEquals` of a struct containing a `SumType` was `const`. That seemed too suspicious to me; I’m afraid it can backfire in any unexpected way. I could have understood something wrong though; worth checking once again.

Should I continue working on lowering the requirements in this PR, or would you prefer to merge it in its current state?

### CODE REVIEW

File: source/argparse/internal/restriction.d [hunk 1]
```diff
@@ -131,7 +131,7 @@ unittest
 {
     auto f = MutuallyExclusive(Config.init, [ArgumentInfo([],[],["--a"]), ArgumentInfo([],[],["--b"]), ArgumentInfo([],[],["--c"])]);
 
-    assert(f(bool[size_t].init, [0,1]));
+    assert(f((bool[size_t]).init, [0,1]));
```
Comment (ljmf00-wekaio) [inline source/argparse/internal/restriction.d:134]: Shouldn't this succeed or its just a styling issue you addressed?

**Review by ljmf00-wekaio — APPROVED** [review]
Looks good

File: source/argparse/internal/restriction.d (hunk 1 above)
Comment (SirNickolas) [reply source/argparse/internal/restriction.d:134]: It is not a styling issue. It worked for you because it is located in a unit test, and unit tests in 3rd-party libraries are not type-checked. (In fact, they are [not even parsed][lex-only-unittest], only lexed. I find this amusing.).

[lex-only-unittest]: https://dlang.org/changelog/2.068.0#lex-only-unittest

**Review by andrey-zherikov — APPROVED** [review]

**Comment by andrey-zherikov** [comment]
> Should I continue working on lowering the requirements in this PR, or would you prefer to merge it in its current state?

Let's do in separate PR
